apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: authservice
  name: authservice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - image: murilocg/authservice:v1.0
          imagePullPolicy: Always
          name: authservice
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: domain
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: clientid
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: clientsecret
