apiVersion: v1
kind: Service
metadata:
  labels:
    app: authservice
  name: authservice
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: authservice
  type: ClusterIP
