apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: murilocg/webapp:v1.0
          imagePullPolicy: Always
          name: webapp
          ports:
            - containerPort: 42000
              name: http
              protocol: TCP
