apiVersion: v1
kind: Service

metadata:
  labels:
    app: webapp
  name: webapp
spec:
  ports:
    - name: http
      port: 4200
      protocol: TCP
      targetPort: 4200
  selector:
    app: webapp
  sessionAffinity: None
  type: LoadBalancer
