apiVersion: v1
kind: Service
metadata:
  name: microservice
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  carga_suporte_mapping
      prefix: /microservice/
      service: microservice
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http-microservice
      targetPort: http-microservice
  selector:
    app: microservice
